sudo: false
language: c
os:
    - linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - cmake

env:
    global:
        - EIGEN_VERSION=3.2.9
          TEST_LANG='python'
          CXX=g++-4.8
          CC=gcc-4.8

    matrix:
        - TEST_LANG='cpp'
        - TEST_LANG='paper'

        - PYTHON_VERSION=2.7
          NUMPY_VERSION=1.9
        - PYTHON_VERSION=2.7
          NUMPY_VERSION=1.10
        - PYTHON_VERSION=2.7
          NUMPY_VERSION=1.11

        - PYTHON_VERSION=3.4
          NUMPY_VERSION=1.9
        - PYTHON_VERSION=3.4
          NUMPY_VERSION=1.10
        - PYTHON_VERSION=3.4
          NUMPY_VERSION=1.11

        - PYTHON_VERSION=3.5
          NUMPY_VERSION=1.9
        - PYTHON_VERSION=3.5
          NUMPY_VERSION=1.10
        - PYTHON_VERSION=3.5
          NUMPY_VERSION=1.11

install:
    - source .ci/travis-$TRAVIS_OS_NAME.sh

script: |
    if [[ $TEST_LANG == paper ]]
    then
      source .ci/build-paper.sh
    elif [[ $TEST_LANG == cpp ]]
    then
      cd cpp
      CTEST_OUTPUT_ON_FAILURE=1 make test
    elif [[ $TEST_LANG == python ]]
    then
      cd python
      py.test -v
    fi
